version: 2
updates:
- package-ecosystem: pip
  open-pull-requests-limit: 30
  directory: "/"
  labels: []
  schedule:
    interval: weekly
    time: "04:00"
- package-ecosystem: github-actions
  open-pull-requests-limit: 30
  directory: "/"
  labels: []
  schedule:
    interval: daily
    time: "04:00"
