name: mkdocs-build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

env:
  PYTHON_VERSION: 3.x

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  pages-build-deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            requirements.txt

      - name: Set up build cache
        uses: actions/cache/restore@v3
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install Python dependencies
        run: |
          pip install mkdocs-material
          pip install mkdocs-material[recommended,git,imaging]
          pip install mkdocs-glightbox
          pip install pillow
          pip install cairosvg
          pip install mkdocs-git-authors-plugin
          pip install mkdocs-git-committers-plugin-2
          pip install mkdocs-git-revision-date-localized-plugin

      - name: Install other dependencies
        run: sudo apt-get install -y build-base jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev cairo-dev libffi-dev libwebp-dev pngquant libcairo2-dev libfreetype6-dev libjpeg-dev libpng-dev libz-dev nodejs

      - name: Build documentation
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GOOGLE_ANALYTICS_KEY: ${{ secrets.GOOGLE_ANALYTICS_KEY }}
        run: |
          mkdocs get-deps
          mkdocs build --clean
          mkdocs --version

      - name: Adjust permissions
        run: |
          chmod -c -R +rX site/ | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Save build cache
        uses: actions/cache/save@v3
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2